/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _OSD_CONFIG_H_RPCGEN
#define _OSD_CONFIG_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct osd_config {
	int width;
	int height;
};
typedef struct osd_config osd_config;

struct encoder {
	int port_id;
	char parameter_name[20];
	char updated_value[20];
	char portname[20];
	char ip_address[20];
	char macaddr[20];
	char type[20];
	char linktype[20];
	char audio[20];
	char format[20];
	char resolution[20];
	char framerate[20];
	char media[20];
	int count;
};
typedef struct encoder encoder;

#define OSD_CONFIG_PROG 0x23451111
#define OSD_CONFIG_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define ConfigData 2
extern  int configdata_1(encoder *, CLIENT *);
extern  int configdata_1_svc(encoder *, struct svc_req *);
extern int osd_config_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define ConfigData 2
extern  encoder * configdata_1();
extern  encoder * configdata_1_svc();
extern int osd_config_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_osd_config (XDR *, osd_config*);
extern  bool_t xdr_encoder (XDR *, encoder*);

#else /* K&R C */
extern bool_t xdr_osd_config ();
extern bool_t xdr_encoder ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_OSD_CONFIG_H_RPCGEN */
