/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "osd_config.h"
#include <string.h>
#include <stdbool.h>
#include "cJSON.h"
#include <time.h>


#define Encoder_msg(fmt, ...) do {\
    time_t t = time(NULL);\
    struct tm *timestamp = localtime(&t);\
    char buffer[26];\
    strftime(buffer, sizeof(buffer), "%Y-%m-%d %H:%M:%S", timestamp);\
    printf("[%s] " fmt, buffer, ##__VA_ARGS__);\
} while (0)

void updateJsonFromFile(const char *filename, const struct encoder *data) {
    // Read cJSON object from temp file
    
    int height, width;
    cJSON *new_data = cJSON_CreateObject();
    
    sscanf(data->resolution, "%d * %d", &width, &height);
    cJSON_AddNumberToObject(new_data, "port_id", data->port_id);
    cJSON_AddStringToObject(new_data, "ip_address", data->ip_address);
    cJSON_AddStringToObject(new_data, "macaddr", data->macaddr);
    cJSON_AddStringToObject(new_data, "type", data->type);
    cJSON_AddStringToObject(new_data, "linktype", data->linktype);
    cJSON_AddStringToObject(new_data, "audio", data->audio);
    cJSON_AddStringToObject(new_data, "format", data->format);
    cJSON_AddStringToObject(new_data, "resolution", data->resolution);
    cJSON_AddStringToObject(new_data, "framerate", data->framerate);
    cJSON_AddNumberToObject(new_data, "width", width);
    cJSON_AddNumberToObject(new_data, "height", height);
    cJSON_AddStringToObject(new_data, "media", data->media);  
    cJSON_AddNumberToObject(new_data, "connect", data->count);
    char *new_json = cJSON_Print(new_data);
   FILE *fp = fopen(filename, "r+");
    if (fp == NULL) {
        printf("Error: Unable to open the file.\n");
        return;
    }


    fp = fopen(filename, "w");
    if (fp == NULL) {
        printf("Error: Unable to open the file for writing.\n");
         cJSON_Delete(new_data);
        cJSON_free(new_json);
        return;
    }

    //printf("%s", json_str);
    fputs(new_json, fp);

    // Close the file
    fclose(fp);

    // Free cJSON object and JSON string
    cJSON_Delete(new_data);
    cJSON_free(new_json);
}

int 
configdata_1_svc(encoder *argp, struct svc_req *rqstp)
{
	 encoder *sev_setting;
	 sev_setting = argp;
	 
	 Encoder_msg("********************************************\n");
	 Encoder_msg("		  Encoder Configuration 			\n");
	 Encoder_msg("********************************************\n");
	 
	 Encoder_msg("Encoder id:	%d \n", sev_setting->port_id);
	 Encoder_msg("Encodername:	%s \n", sev_setting->portname);
	 Encoder_msg("IP address:	%s \n", sev_setting->ip_address);
	 Encoder_msg("Mac Address:	%s \n", sev_setting->macaddr);
	 Encoder_msg("Encoder type:	%s \n", sev_setting->type);
	 Encoder_msg("Linktype:		%s \n", sev_setting->linktype); 
	 Encoder_msg("Audio Type:	%s \n", sev_setting->audio);
	 Encoder_msg("Audio format:	%s \n", sev_setting->format);
	 Encoder_msg("Resolution:	%s \n", sev_setting->resolution);
	 Encoder_msg("Framerate:	%s \n", sev_setting->framerate);
 	 Encoder_msg("virtual_media:	%s  \n", sev_setting->media);
 	 Encoder_msg("No of Decoder: %d \n", sev_setting->count);
	 printf("\n");	
 	 
 	 updateJsonFromFile("/home/root/appfs/config.json", sev_setting);
 		
	 
	 return 0;//sev_setting;
}
