/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include <unistd.h>
#include <time.h>
#include "rpc_client.h"

encoder enc_setting;
void setConfigdata(char *encoder_ip, encoder enc_setting)
{

	CLIENT *clnt;
	int result = 1;
//	port_setting  p_setting;
	
	result = (encoder *) malloc(sizeof(encoder));
	if (result == 0)
	{
		perror("memory allocation failed");
		exit(EXIT_FAILURE);
	}

#ifndef	DEBUG
	clnt = clnt_create (encoder_ip, OSD_CONFIG_PROG, OSD_CONFIG_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (encoder_ip);
		exit (1);
	}
#endif	
	result = configdata_1(&enc_setting, clnt);	
	if (result == 1) {
		clnt_perror (clnt, "call failed");
	}
	
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif

}

void callback()
{
	char * encoderIp;
	//printf("In callback Trigger name: %s\n", trigger);
	
	printf("********** Encoder Changes occured **************\n");
	if (strcmp(trigger, "port_trigger") == 0)
	{
		//mysql_free_result(result);

		char query[520]; // Change the size according to your query
		snprintf(query, sizeof(query), "SELECT p.port_id, p.column_name, p.new_value, pn.portname, pn.ip_address, pn.macaddr, pn.type, pn.linktype, pn.audio, pn.format, pn.resolution, pn.framerate, pn.media, pn.connect FROM port_log p JOIN portname pn ON p.port_id = pn.id WHERE p.updated_at = (SELECT MAX(updated_at) FROM port_log);");
		if (mysql_query(con, query)) {
		
  		fprintf(stderr, "SELECT * FROM Error: %s\n", mysql_error(con));
    	mysql_close(con);
    	exit(1);
		}
		
       	result = mysql_store_result(con);
		if (result == NULL) {
		fprintf(stderr, "mysql_store_result() failed\n");
		mysql_close(con);
		exit(1);
		}

		
		while ((row = mysql_fetch_row(result))) {
		enc_setting.port_id = atoi(row[0]);
		strcpy(enc_setting.parameter_name ,row[1]); 
		strcpy(enc_setting.updated_value ,row[2]); 
		strcpy(enc_setting.portname ,row[3]); 
		strcpy(enc_setting.ip_address, row[4]);
		strcpy(enc_setting.macaddr , row[5]);
		strcpy(enc_setting.type , row[6]);
		strcpy(enc_setting.linktype , row[7]);
		strcpy(enc_setting.audio , row[8]);
		strcpy(enc_setting.format , row[9]);
		strcpy(enc_setting.resolution , row[10]);
		strcpy(enc_setting.framerate , row[11]);
		strcpy(enc_setting.media , row[12]);
		enc_setting.count = atoi(row[13]);
		
		Decoder_msg("*************************************************\n");
	 	Decoder_msg("		  Updated Configuration 			\n");
	 	Decoder_msg("*************************************************\n");
	 	
		Decoder_msg("Encoder id:		%d \n", atoi(row[0]));
		Decoder_msg("Changed Parameter:	%s \n", row[1]);
		Decoder_msg("New value:		%s \n", row[2]);
		Decoder_msg("Encoder Name:		%s \n", row[3]);
		Decoder_msg("IP address:		%s \n", row[4]);
		Decoder_msg("Mac Address:		%s \n", row[5]);
		Decoder_msg("Encoder type:		%s \n", row[6]);
		Decoder_msg("Linktype:			%s \n", row[7]);
		Decoder_msg("Audio Type:		%s \n", row[8]);
		Decoder_msg("Audio format:		%s \n", row[9]);
		Decoder_msg("Resolution		%s \n", row[10]);
		Decoder_msg("Framerate			%s \n", row[11]);
	 	Decoder_msg("virtual_media:		%s \n", row[12]);
	 	Decoder_msg("No of Decoder 		%d \n", atoi(row[13]));
	 	printf("\n");
	 	
    	setConfigdata(encoder_ip, enc_setting);
}
}
}
char* checkTrigger(void (*fn)(void) )
{
		set_bit =1;
		if (mysql_query(con, "SELECT trigger_name FROM trigger_log WHERE event_time = (SELECT MAX(event_time) FROM trigger_log);"))
		{
			fprintf(stderr, "Error querying database: %s\n", mysql_error(con));
			mysql_close(con);
		}

		result = mysql_store_result(con);

		while ((row = mysql_fetch_row(result)) != NULL)
		{
			trigger = row[0];
			// printf("Trigger name: %s\n", trigger);
		}	//end of while
	return *trigger;

} //End of checktrigger function

int main (int argc, char *argv[])
{
	encoder_ip = argv[1];
	if (argc < 1) {
		// printf ("usage: %s server_encoder_ip number \n", argv[0]);
		exit (1);
	}
	con = mysql_init(NULL);
	
	if (mysql_real_connect(con, "localhost", "root", "Nikita@2207", "kvm", 0, NULL, 0) == NULL)
		printf("mysql_real_connect() failed\n");
	
	else
		printf("********** Database Connection Established **************\n");

	//registering callback with function pointer	
	void (*fn_ptr)( void ) = &callback;

	//calling callback with function pointer

		while(1){

		if(checkTrigger(fn_ptr)){
			callback();
			sleep(5);
		}
		else
			sleep(5);
		mysql_free_result(result);
}
	
	mysql_close(con);
return 0;	
}
